### ISSUE TITLE
chadcord 2?

### ISSUE THREAD

**Issue by nin0-dev** [LockBlock-dev/Vencord-without-rainbows#1]
### Content

h

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by LockBlock-dev** [comment]
what

**Comment by korbosoft** [comment]
I wouldn't bet on github keeping this up, last time someone made an anti-woke vencord fork (chadcord), it got wiped off of github

**Comment by LockBlock-dev** [comment]
> I wouldn't bet on github keeping this up, last time someone made an anti-woke vencord fork (chadcord), it got wiped off of github

I just removed their cloud integration and the donation stuff, I'm GPL compliant afaik

**Comment by nin0-dev** [comment]
1- you are an idiot2- issue isn’t gpl compliance, it’s the homophobia3- did i mention you being an idiotOn Aug 9, 2024, at 12:48 PM, LockBlock-dev ***@***.***> wrote:﻿

I wouldn't bet on github keeping this up, last time someone made an anti-woke vencord fork (chadcord), it got wiped off of github

I just removed their cloud integration and the donation stuff, I'm GPL compliant afaik

**Comment by SomeRandom-Dev** [comment]
i do not believe this to be a useful issue, in fact i would instead mark this fork as a bloat-free version of vencord

**Comment by LockBlock-dev** [comment]
> 1- you are an idiot2- issue isn’t gpl compliance, it’s the homophobia3- did i mention you being an idiotOn Aug 9, 2024, at 12:48 PM, LockBlock-dev ***@***.***> wrote:﻿ I wouldn't bet on github keeping this up, last time someone made an anti-woke vencord fork (chadcord), it got wiped off of github I just removed their cloud integration and the donation stuff, I'm GPL compliant afaik —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

I am not being homophobic at all, I just removed things I did not want in the mod. How would I be homophobic when I did not remove plugins like pronounsDB? Now if you have nothing more to add than baseless attacks I will be closing this issue.

**Comment by LennyMcLennington** [comment]
SNEED

**Comment by LennyMcLennington** [comment]
> I wouldn't bet on github keeping this up, last time someone made an anti-woke vencord fork (chadcord), it got wiped off of github

@korbosoft @nin0-dev GitHub doesn't take down projects for being some vague definition of "homophobic" there has to be some concrete violation of their terms like some license violation or some slurs being used or something like that. In conclusion, SNEED.
