### ISSUE TITLE
License Violation

### ISSUE THREAD

**Issue by Vendicated** [LockBlock-dev/Vencord-without-rainbows#2]
### Content

You can't just relicense GPL code to AGPL man that's not how shit works

Please fix or we might have to take additional steps

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
this is also not allowed lol you
- can't just erase names or the original year
- can't just merge your copyright into our copyright. there have to be two lines indicating you made changes, like
```
* Copyright (c) 2023 Vendicated and Vencord Contributors
* Copyright (c) 2024 The entire circus
```

![image](https://github.com/user-attachments/assets/e7e7c576-8695-4b16-815e-809a4d542a77)

**Comment by crueter** [comment]
@LockBlock-dev please revert this commit.
